# If you want the output to be verbose AF.
debug: false
# Measurement input topics.
usbl_meas_topic: /sam/sim/usbl
imu_meas_topic: /sam/sim/imu
depth_meas_topic: /sam/dr/depth
dvl_meas_topic: /sam/sim/dvl
odom_meas_topic: /sam/relative/odom
dr_meas_topic: /sam/enu/odom
optical_meas_topic: /sam/perception/target_pose

# ------------- PRIORS -------------
# Standard deviation of the prior information's translation components [m].
prior_x_stddev: 1.0
prior_y_stddev: 1.0
prior_z_stddev: 0.1
# Standard deviation of the prior information's rotation components [rad].
prior_roll_stddev: 0.00001
prior_pitch_stddev: 0.00001
prior_yaw_stddev: 0.00001
# Prior standard deviation on the target's velocity [m/s].
prior_vel_x_stddev: 0.001
prior_vel_y_stddev: 0.001
prior_vel_z_stddev: 0.1
# ------------- PRIORS -------------

# ------------- NOISE --------------
# USBL position noise.
usbl_x_stddev: 1.0
usbl_y_stddev: 1.0
usbl_z_stddev: 2.5
# Initial Bias (if previously estimated)
#init_accel_bias_x: -1.18361506
#init_accel_bias_y: 0.11160959
#init_accel_bias_z: -0.0775727739
#init_omega_bias_x: 0.0115292506
#init_omega_bias_y: -0.00969517923
#init_omega_bias_z: -0.00149639507
init_accel_bias_x: 0.0869525
init_accel_bias_y: 0.183961944
init_accel_bias_z: -0.0265742397
init_omega_bias_x: 0.00380564106
init_omega_bias_y: -0.000306797758
init_omega_bias_z: 0.0018205596
# Initial Bias noise.
init_accel_bias_stddev: 0.50000035
init_omega_bias_stddev: 0.000005177
# VALUES FOR SBG ELLIPSE A
# Standard deviation for the linear acceleration measurements [m/s2].
accel_noise_x: 0.00052925
accel_noise_y: 0.00052925
accel_noise_z: 0.00052925
# Bias standard deviation for the linear acceleration measurements [m/s2]
accel_bias_x: 0.00000872151
accel_bias_y: 0.00000872151
accel_bias_z: 0.00000872151
# Standard deviation for the angular velocity measurements [???].
omega_noise_x: 0.0000843214
omega_noise_y: 0.0000843214
omega_noise_z: 0.0000843214
# Bias standard deviation for the angular velocity measurements [rad/s]
omega_bias_x: 0.00000305698
omega_bias_y: 0.00000305698
omega_bias_z: 0.00000305698
# Measurement frequency [Hz].
imu_frequency: 25.0
# ------------- NOISE --------------

# ------------- EXTRINSICS --------------
# Setup the sensor extrinsic calibrations. The extrinsic rotations are
# built using gtsam::Rot3::RzRyRx, see their documentation for angle convention.
# Angles increase counterclockwise when looking from the unchanged axis.
# Rotation multiplication is done in yaw-pitch-roll convention.
# Chaser's camera's extrinsic calibration params. base->camera.
camera_extrinsics_yaw: 1.5707 # [rad]
camera_extrinsics_pitch: 0.0 # [rad]
camera_extrinsics_roll: 1.5707 # [rad]
camera_extrinsics_x: -0.6561        # [m]
camera_extrinsics_y: 0.003        # [m]
camera_extrinsics_z: 0.4935        # [m]
# Chaser's usbl's extrinsic calibration. base->cusbl.
ch_usbl_extrinsics_yaw: 0.0   # [rad]
ch_usbl_extrinsics_pitch: 0.0 # [rad]
ch_usbl_extrinsics_roll: 0.0 # [rad]
ch_usbl_extrinsics_x: 1.6103  # [m]
ch_usbl_extrinsics_y: 0.0966  # [m]
ch_usbl_extrinsics_z: 0.4802  # [m]

# target's fiducials's extrinsic calibration. sbg->fiducials center.
fiducials_extrinsics_yaw: 1.5707  # [rad]
fiducials_extrinsics_pitch: 0.0 # [rad]
fiducials_extrinsics_roll: -1.5707 # [rad]
fiducials_extrinsics_x: 0.49        # [m]
fiducials_extrinsics_y: 0.0        # [m]
fiducials_extrinsics_z: 2.13        # [m]
# target's usbl's extrinsic calibration. sbg->tusbl.
tgt_usbl_extrinsics_yaw: 0.0      # [rad]
tgt_usbl_extrinsics_pitch: 0.0    # [rad]
tgt_usbl_extrinsics_roll: 3.14159 # [rad]
tgt_usbl_extrinsics_x: 0.345        # [m]
tgt_usbl_extrinsics_y: 0.0        # [m]
tgt_usbl_extrinsics_z: 2.13        # [m]
# ------------- EXTRINSICS --------------

# ------ OPTICAL OUTLIERS --------------
# Previously identified outliers in the data.
optical_outliers: [0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  22,  23,  24,  27,  28,
        29,  32,  34,  36,  37,  38,  39,  41,  44,  45,  46,  47,  48,
        49,  50,  52,  54,  55,  56,  57,  58,  59,  60,  62,  63,  64,
        71,  74,  75,  76,  77,  78,  79,  82, 138, 323, 332, 353, 354,
       399, 400, 401, 402, 456, 458, 489, 493, 494, 557, 650, 653, 655]



